 College Degree vs Income

## Graphs
```{r}
library(viridis)
```


```{r}
df_philly_2015 %>% mutate(City_Suburb = ifelse(county_code == 'Philadelphia','City','Suburb')) %>% 
  ggplot( aes(x = college_deg, y = median_income))+
  geom_point(aes(color = City_Suburb), alpha = .5, size = 2)+
  scale_y_continuous(labels = function(x){paste0("$", x/1000, "K")})+
  scale_x_continuous(labels = function(x){paste0(x, "%")})+
  labs(
    title = 'Median Income vs. College Degree in Philadelphia',
    x = 'College Degree',
    y = 'Median Income',
    color = 'City or Suburb'
  )+
  theme_classic()
```

# High Skill vs Income

## Graphs
```{r}
df_philly_2015 %>% mutate(City_Suburb = ifelse(county_code == 'Philadelphia','City','Suburb')) %>% 
  ggplot( aes(x = perc_over15_high_skill, y = median_income))+
  geom_point(aes(color = City_Suburb), alpha = .5, size = 2)+
  scale_y_continuous(labels = function(x){paste0("$", x/1000, "K")})+
  scale_x_continuous(labels = function(x){paste0(x, "%")})+
  labs(
    title = 'Median Income vs. Skilled Labor in Philadelphia',
    x = 'Skilled Labor',
    y = 'Median Income',
    color = 'City or Suburb'
  )+
  theme_classic()
```


# Homeownership

## Graphs
```{r}
ggplot(df_philly_2015, aes(x = reorder(county_code, home_ownership), y = median_income)) +
  geom_violin() +
  geom_point(position = position_jitter(width = 0.4), alpha = .35, aes(color = home_ownership)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  scale_color_viridis(name = "% Home Ownership",
                      breaks = seq(0,100,25),
                      labels = function(x){paste0(x, "%")}) +
  scale_y_continuous(labels = function(x){paste0("$", x/1000, "K")}) +
    labs(
    x = "County",
    y = "Median Income",
    title = "Home Ownership in Philly and its Suburbs",
    subtitle = "Vs. Philadelphia Area Median Income"
  ) +
  geom_hline(yintercept = median(df_philly_2015$median_income), color = "red", linetype = "dashed")+
  theme_bw()+
  theme(axis.text.x = element_text(colour = text_color))
```

# Income

## Data Selection
```{r}
income_Philly <- df_philly_2015 %>%
  group_by(county_code)%>%
  summarise(mean_inc = mean(median_income))%>%
  mutate(deviation= mean_inc - income$mean)%>%
  arrange(desc(mean_inc))
```

## Graphs
```{r}
ggplot(income_Philly, aes(x = reorder(county_code, deviation), y = deviation,
           fill = deviation >0))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_discrete(name = "", labels = c("Below Average", "Above Average"))+
  labs(
    title="Household income in Philadelphia",
    subtitle="Vs. Philadelphia Area Average Median Income, $66K",
    x = "City",
    y = "Amount Difference"
  )+
  theme_bw()+
  theme(axis.text.y = element_text(colour = text_color)) +
  scale_y_continuous(labels = function(x){paste0("$", x/1000, "K")}) 
```



