---
title: "Philly Education"
---

# Third Grade Reading Scores

## Graphs
```{r}
df_philly_2015 %>% 
  mutate(Area = ifelse(county_code == "Philadelphia", "City", "Suburb")) %>% 
  ggplot(aes(x = county_code, y = third_g_math + third_g_read, fill = Area, alpha = Area)) +
  geom_boxplot(outlier.alpha=0) +
  geom_hline(data = df_philly_2015, aes(yintercept = mean(third_g_read, na.rm = TRUE) + mean(third_g_math, na.rm = TRUE)), col = "red",linetype='dotted') + 
  scale_fill_manual(values = c("#69b3a2", "grey")) +
  scale_alpha_manual(values=c(1,0.1)) +
  theme_classic() +
  labs(title = "2015 Philadelphia 3rd Grades Reading and Math Scores", 
       subtitle = "Vs. National Average", 
       x = "County", 
       y = "3rd Grades Reading & Math scores")
```

----
# Highschool Graduation Rates 

## Data Collection
```{r}
grad_rates_philly <- df_philly %>%
  group_by(county_code,year)%>%
  summarise(mean_grad = mean(hs_grads))

grad_rates_good <- grad_rates_philly %>% filter(county_code %in% c('Philadelphia',
    'Bucks',
    'Chester',
    'Delaware'))

grad_rates_bad <-  grad_rates_philly %>% filter(county_code %in% c("Montgomery"))
```

```{r}
grad_color = c("black", "black", "black", "black", "red")
ggplot() + 
  geom_point(data = grad_rates_philly,aes(x = mean_grad, y = county_code, color = factor(year)), size = 4, alpha = .8)+
  geom_line(data = grad_rates_good, aes(x = mean_grad, y = county_code), arrow = arrow(length=unit(0.20,"cm"), ends="last", type = "closed"))+
  geom_line(data = grad_rates_bad, aes(x = mean_grad, y = county_code), arrow = arrow(length=unit(0.30,"cm"), ends="first", type = "closed"))+
  labs(title = "Change in High School Graduation Rate", 
       x = "Percent Graduated",
       y = "County",
       color = 'Year')+
  theme_classic()+
  theme(panel.grid.major.x=element_line(), axis.text.y = element_text(colour = grad_color))+
  scale_x_continuous(
            breaks=seq(50, 100, 5),
            labels = function(x){paste0(x*1, '%')}
            )
```

----
# AP Classes 

## Data Collection
```{r}
ap_philly<- df_philly_2015 %>%
  filter(county_code == "Philadelphia" & median_income < income$mean)
philly_wealthy <- df_philly %>%
  filter(county_code== "Philadelphia" & median_income > income$mean)

ap_sub_philly<- df_philly_2015 %>%
  filter(county_code !="Philadelphia" & median_income < income$mean)
sub_philly_wealthy <- df_philly %>%
  filter(county_code != "Philadelphia" & median_income > income$mean)
```

##  Graphs
```{r}
colors <- c("More than $66K" = "light blue", "Less than $66K" = "pink")

ggplot()+
  geom_density(aes(AP_students, fill= "Less than $66K"), alpha = .2, data = ap_philly)+
  geom_density(aes(AP_students, fill= "More than $66K"), alpha = .2,  data = philly_wealthy)+
  labs(
    title="AP Courses vs. Income",
    subtitle="Philadelphia",
    x="Ratio of Upper Level Students in AP Courses",
    y="Frequency",
    color = colors,
    fill = 'AP Students'
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())

ggplot()+
  geom_density(aes(AP_students, fill="Less than $66K"), alpha = .2, data = ap_sub_philly)+
  geom_density(aes(AP_students, fill="More than $66K"), alpha = .2,  data = sub_philly_wealthy)+
  labs(
    title="AP Courses vs. Income",
    subtitle="Philadelphia Suburban Areas",
    x="Ratio of Upper Level Students in AP Courses",
    y="Frequency",
    color = colors,
    fill = 'AP Students'
  )+
  theme_classic()+
  theme(panel.grid.major.x=element_line())
```